/**
 * Text Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalyzeTextRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TextAnalyzerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Analyze text for character categories
     * Analyzes the input text and returns letter frequencies
     * @param analyzeTextRequest 
     */
    analyzeText(analyzeTextRequest: AnalyzeTextRequest, extraHttpRequestParams?: any): Observable<{ [key: string]: number; }>;

}
