/**
 * Text Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalyzeTextRequest { 
    /**
     * Type of analysis (e.g. \"vowels\" or \"consonants\" or \"nonAeiou\")
     */
    type: string;
    /**
     * The text to analyze
     */
    input: string;
}

